custom_proxy_group=❄️ 节点选择`select`[]🇯🇵 夜桜秘湯`[]🇭🇰 蜡笔王国`[]🇹🇼 蓬萊玉枝`[]🇸🇬 星空浴場`[]🇺🇸 陽光海岸`[]♨️ 手动选择`[]♻️ 自动选择`[]🔯 故障转移`[]🔮 负载均衡`[]🏮 冷门负载
custom_proxy_group=♨️ 手动选择`select`.*
custom_proxy_group=🎏 漏网之鱼`select`[]❄️ 节点选择`[]DIRECT
custom_proxy_group=🇯🇵 夜桜秘湯`select`(🇯🇵|JP|Japan|日本|东京|大阪|埼玉|[^-]日)`[]REJECT
custom_proxy_group=🇭🇰 蜡笔王国`select`(🇭🇰|HK|Hong Kong|HongKong|[^-]港)`[]REJECT
custom_proxy_group=🇹🇼 蓬萊玉枝`select`(🇹🇼|TW|Taiwan|[^-]台|新北|彰化|HINET)`[]REJECT
custom_proxy_group=🇸🇬 星空浴場`select`(🇸🇬|SG|Singapore|新加坡|狮城|[^-]新)`[]REJECT
custom_proxy_group=🇺🇸 陽光海岸`select`(🇺🇸|US|United States|[^-]美|波特兰|达拉斯|俄勒冈|凤凰城|费利蒙|硅谷|拉斯维加斯|洛杉矶|圣何塞|圣克拉拉|西雅图|芝加哥)`[]REJECT
