[custom]
;由外部配置中所定义的值会覆盖主程序目录中配置文件里的内容

;设置分组标志位
custom_proxy_group=❄️ 节点选择`select`[]🇯🇵 夜桜秘湯`[]🇭🇰 蜡笔王国`[]🇺🇸 陽光海岸

;自定义 Emoji
add_emoji=true
remove_old_emoji=true
emoji=(Bandwidth|expire|官|流量|时间|应急|更新|订阅|失联|剩余|永久|地址|升级|群|期),🏳️‍🌈
emoji=(HK[G]?|Hong.*?Kong|HKT|HKBN|HGC|WTT|CMI|[^-]港),🇭🇰
emoji=(TW[N]?|Taiwan|新北|彰化|CHT|台[^-]|[^-]台|HINET),🇹🇼
emoji=(JP[N]?|Japan|Tokyo|Osaka|Saitama|日本|东京|大阪|埼玉),🇯🇵
emoji=(K[O]?R|KR|Korea|首尔|韩|韓),🇰🇷
emoji=(SG[P]?|Singapore|新加坡|狮城|[^-]新),🇸🇬
emoji=(US[A]?|America|United.*?States|美国|纽约|波特兰|达拉斯|俄勒冈|凤凰城|费利蒙|硅谷|拉斯维加斯|洛杉矶|圣何塞|圣克拉拉|西雅图|芝加哥),🇺🇸
emoji=(AU[S]?|Australia|Sydney|澳大利亚|澳洲|悉尼),🇦🇺
emoji=(Afghanistan|阿富汗),🇦🇫
emoji=(Africa|南非),🇿🇦
emoji=(Albania|阿尔巴尼亚),🇦🇱
emoji=(Albania|阿尔巴尼亚),🇦🇱
emoji=(Antarctica|南极),🇦🇶
emoji=(Antigua and Barbuda|安提瓜和巴布达),🇦🇬
emoji=(Arabia|沙特),🇸🇦
emoji=(Argentina|阿根廷),🇦🇷
emoji=(Armenia|亚美尼亚),🇦🇲
emoji=(Ascension|阿森松),🇦🇨
emoji=(Austria|Vienna|奥地利|维也纳),🇦🇹
emoji=(Azerbaijan|阿塞拜疆),🇦🇿
emoji=(Belgium|比利时),🇧🇪
emoji=(Bengal|孟加拉),🇧🇩
emoji=(Bengal|孟加拉),🇧🇩
emoji=(Bosnia|Herzegovina|波黑共和国|波士尼亚与赫塞哥维纳),🇧🇦
emoji=(Brazil|Paulo|巴西|圣保罗),🇧🇷
emoji=(Bulgaria|保加利亚),🇧🇬
emoji=(CA[N]?|Canada|Toronto|Montreal|Vancouver|加拿大|蒙特利尔|温哥华|楓葉|枫叶),🇨🇦
emoji=(Cambodia|柬埔寨),🇰🇭
emoji=(Chile|智利),🇨🇱
emoji=(Colombia|哥伦比亚),🇨🇴
emoji=(Costa Rica|哥斯达黎加),🇨🇷
emoji=(Croatia|克罗地亚),🇭🇷
emoji=(Cyprus|塞浦路斯),🇨🇾
emoji=(Czech|捷克),🇨🇿
emoji=(DE[U]|Germany|法兰克福|德(国|意志)|中德|^德$),🇩🇪
emoji=(D[N]?|Denmark|丹麦),🇩🇰
emoji=(ES[P]?|Spain|西班牙),🇪🇸
emoji=(Ecuador|厄瓜多尔),🇪🇨
emoji=(Ecuador|厄瓜多尔),🇪🇨
emoji=(Egypt|埃及),🇪🇬
emoji=(Estonia|爱沙尼亚),🇪🇪
emoji=(Europe|欧洲),🇪🇺
emoji=(FR[A]?|France|Paris|法国|巴黎),🇫🇷
emoji=(Finland|Helsinki|芬兰|赫尔辛基),🇫🇮
emoji=(Georgia|格鲁吉亚),🇬🇪
emoji=(Greece|希腊),🇬🇷
emoji=(Hungary|匈牙利),🇭🇺
emoji=(IN[D]?|India|Mumbai|印度|孟买|加尔各答|贾坎德|泰米尔纳德),🇮🇳
emoji=(IS[L]?|Iceland|冰岛),🇮🇸
emoji=(Indonesia|Jakarta|印尼|印度尼西亚|雅加达),🇮🇩
emoji=(Iran|伊朗),🇮🇷
emoji=(Ireland|Dublin|爱尔兰|都柏林),🇮🇪
emoji=(Israel|以色列),🇮🇱
emoji=(Italy|Milan|意大利|米兰),🇮🇹
emoji=(Jordan|约旦),🇯🇴
emoji=(Kazakhstan|哈萨克斯坦),🇰🇿
emoji=(Kenya|肯尼亚),🇰🇪
emoji=(Kyrgyzstan|吉尔吉斯斯坦),🇰🇬
emoji=(Latvia|拉脱维亚),🇱🇻
emoji=(Lietuvos|立陶宛),🇱🇹
emoji=(Luxemburg|Luxembourg|卢森堡),🇱🇺
emoji=(Macao|澳门|CTM),🇲🇴
emoji=(Macedonia|北马其顿),🇲🇰
emoji=(Malaysia|马来|MY),🇲🇾
emoji=(Mann|马恩岛),🇮🇲
emoji=(Mexico|墨西哥),🇲🇽
emoji=(Moldova|摩尔多瓦),🇲🇩
emoji=(Mongolia|Монголулс|蒙古),🇲🇳
emoji=(Morocco|摩洛哥),🇲🇦
emoji=(Morocco|摩洛哥),🇲🇦
emoji=(Myanmar|缅甸),🇲🇲
emoji=(NL[D]?|Netherlands|荷兰|阿姆斯特丹),🇳🇱
emoji=(Nepal|尼泊尔),🇳🇵
emoji=(Nepal|尼泊尔),🇳🇵
emoji=(New Zealand|新西兰|纽西兰),🇳🇿
emoji=(Nigeria|尼日利亚),🇳🇬
emoji=(North.*?Korea|朝鲜),🇰🇵
emoji=(Norway|挪威),🇳🇴
emoji=(P[O]?L|Poland|波兰),🇵🇱
emoji=(Pakistan|巴基斯坦),🇵🇰
emoji=(Panama|巴拿马),🇵🇦
emoji=(Peru|秘鲁),🇵🇪
emoji=(Philippines|菲律宾),🇵🇭
emoji=(Portugal|葡萄牙),🇵🇹
emoji=(Puerto.*?Rico|波多黎各),🇵🇷
emoji=(RU[S]?|Russia|Moscow|Petersburg|Siberia|伯力|莫斯科|圣彼得堡|西伯利亚|新西伯利亚|哈巴罗夫斯克|俄罗斯|[^-]俄),🇷🇺
emoji=(Romania|罗马尼亚),🇷🇴
emoji=(Serbia|塞尔维亚),🇷🇸
emoji=(Slovenia|斯洛文尼亚),🇸🇮
emoji=(Slovensko|斯洛伐克),🇸🇰
emoji=(Sweden|瑞典),🇸🇪
emoji=(Switzerland|Zurich|瑞士|苏黎世),🇨🇭
emoji=(Thailand|泰国|曼谷),🇹🇭
emoji=(Tunisia|突尼斯),🇹🇳
emoji=(Turkey|土耳其|伊斯坦布尔),🇹🇷
emoji=(UAE|Dubai|阿联酋|迪拜),🇦🇪
emoji=(UK|GB[R]?|England|United.*?Kingdom|London|英国|[^-]英|伦敦),🇬🇧
emoji=(Ukraine|UA|乌克兰),🇺🇦
emoji=(Uruguay|乌拉圭),🇺🇾
emoji=(Vatican|梵蒂冈),🇻🇦
emoji=(Venezuela|委内瑞拉),🇻🇪
emoji=(Venezuela|委内瑞拉),🇻🇪
emoji=(Vietnam|越南),🇻🇳
emoji=(C[H]?N|China|回国|中国[^-]|江苏[^-]|北京[^-]|上海[^-]|广州[^-]|深圳[^-]|杭州[^-]|常州[^-]|徐州[^-]|青岛[^-]|宁波[^-]|镇江[^-]|成都[^-]|back),🇨🇳

;在Clash配置文件中proxies的生成风格
clash_proxies_style=flow
clash_proxy_groups_style=flow

;用于包含或排除节点关键词的选项会覆盖主程序目录中的配置文件里的内容
include_remarks=(日本|🇯🇵|JP|Japan|港|🇭🇰|HK|Kong|新加坡|狮城|🇸🇬|SG|Singapore|美国|🇺🇸|US|America|United.*?States|(?<!\d)((?i)0[.x×])(?!\d)|s4|s801)
exclude_remarks=(?<!\d)(1.[4-9]|((?i)2.?([1-9]|[x×])))(?!\d)|(?<![sc.\d])(0?[2-9]|[1-9][0-9])(?!\d)|(?<=家宽|美).*?(HK|US)|(高级|标准).*?(专线.*?(日|狮|港|美))|(?<=v1).*?(日本・|香港・|美国・)|(日本|港|美).*?线路|AUS|中国|ソフトバンク|オプテージ|auひかり|海|油尖旺|美国(高级|实验性)|PVCC|Magic|CDN|公用|南部|俄罗斯

;用于自定义重命名的选项 会覆盖 pref.ini 里的内容
rename=JMS-\d+@c\d+s4\.portablesubmarines\.com:\d+@Japan SoftBank s4
rename=JMS-\d+@c\d+s801\.portablesubmarines\.com:\d+@USA Sin801 0.1x
rename=无限制-白嫖优化-连接数/BT/PT/矿池-1Gbps@ 

;自定义规则
enable_rule_generator=false
overwrite_original_rules=false

;自定义基础配置
clash_rule_base=https://raw.githubusercontent.com/ikali/ACL4SSR/main/Clash/base/ClashConfig.yml
