#---------------------------------------------------#
# 配置文件需要放置在 $HOME/.config/clash/config.yml
# 或者运行目录下的config.yml
#---------------------------------------------------#

port: 7890
ipv6: false
log-level: warning
find-process-mode: always
external-controller: 127.0.0.1:9090
external-ui: ui

dns:
  enable: true
  prefer-h3: true
  listen: 0.0.0.0:53
  default-nameserver: [223.5.5.5, 182.254.116.116]
  nameserver: [https://106.52.218.142/verse, https://1.15.50.48/verse]
