#---------------------------------------------------#
# 配置文件需要放置在 $HOME/.config/clash/config.yml
# 或者运行目录下的config.yml
#---------------------------------------------------#

port: 7890
ipv6: false
log-level: silent
external-controller: 127.0.0.1:9090
external-ui: ui

dns:
  enable: true
  listen: 0.0.0.0:53
  nameserver: [https://1.0.0.2/dns-query]
  nameserver-policy: {"geosite: cn, private": [119.29.29.29]}
